# Generated by Django 2.0.2 on 2018-11-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20181120_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image1',
            new_name='image',
        ),
    ]
